/**    biweekly-contest-138

You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:

Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).

 

Example 1:

Input: num1 = 1, num2 = 10, num3 = 1000

Output: 0

Explanation:

On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".

The 1st digit of the key is min(0, 0, 1).
The 2nd digit of the key is min(0, 0, 0).
The 3rd digit of the key is min(0, 1, 0).
The 4th digit of the key is min(1, 0, 0).
Hence, the key is "0000", i.e. 0.  */

class Solution {
    public static int generateKey(int num1, int num2, int num3) {
       
        String str1 = String.format("%04d", num1);
        String str2 = String.format("%04d", num2);
        String str3 = String.format("%04d", num3);

        StringBuilder key = new StringBuilder();

        for (int i = 0; i < 4; i++) {
            char minDigit = minDigit(str1.charAt(i), str2.charAt(i), str3.charAt(i));
            key.append(minDigit);
        }

        return Integer.parseInt(key.toString());
    }

    private static char minDigit(char a, char b, char c) {
        return (char) Math.min(a, Math.min(b, c));
    }

    public static void main(String[] args) {
        
        int num1 = 1, num2 = 10, num3 = 1000;
        System.out.println(generateKey(num1, num2, num3)); // Output: 0

        num1 = 987; num2 = 879; num3 = 798;
        System.out.println(generateKey(num1, num2, num3)); // Output: 777

        num1 = 1; num2 = 2; num3 = 3;
        System.out.println(generateKey(num1, num2, num3)); // Output: 1

        // Additional test cases
        num1 = 3456; num2 = 2345; num3 = 1234;
        System.out.println(generateKey(num1, num2, num3)); // Output: 1234

        num1 = 9999; num2 = 8888; num3 = 7777;
        System.out.println(generateKey(num1, num2, num3)); // Output: 7777

        num1 = 500; num2 = 60; num3 = 7;
        System.out.println(generateKey(num1, num2, num3)); // Output: 0000
    }
}

     
    
